theme: jekyll-theme-primer
# theme: jekyll-theme-slate
title: Corpus of Hate speech in Online Comments from German Newspapers (HOCON34k)
description: A corpus of 34,223 annotated german hate speech comments from online newspapers
