theme: jekyll-theme-primer
# theme: jekyll-theme-slate
title: Corpus of German misogynistic hatespeech posts (GMHP7k)
description: A corpus of 6000 annotated german social media posts from six brand pages on Facebook
